app.base-url=http://localhost:8080
keycloak.url=http://localhost:8081

test.user.username=user1
test.user.password=password1
test.user.email=user1@example.com

playwright.headless=true
playwright.slow-mo=0
playwright.timeout=30000
