services:
  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_USER: qur_user
      POSTGRES_PASSWORD: qur_password
      POSTGRES_DB: qur_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_qur_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_qur_data: