spring:
  application:
    name: QuR
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/qur_db
    username: qur_user
    password: qur_password
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8081/realms/qur}
        registration:
          keycloak:
            provider: keycloak
            client-id: ${OAUTH2_CLIENT_ID:qur-client}
            client-secret: ${OAUTH2_CLIENT_SECRET:tItZt1hOUxxNFFaeuvL35r0lQZva3et6}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email